version: 2.1

jobs:
  build-portal:
    docker:
      - image: circleci/golang:1.15
      
    steps:
      - checkout
      
      - setup_remote_docker:
          version: 19.03.13
          
      - run: |
          if [ -z $(git diff --name-only HEAD HEAD~1 | grep portal | head -n 1 ) ]; then 
          
            circleci-agent step halt
            
          else
          
            if [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]]; then
                TAG="latest"
            else
                TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
            fi
            docker build -t topiaas/portal:$TAG ./portal
            docker build -t topiaas/portalworker:$TAG -f ./portal/Dockerfile.worker ./portal
            echo "$DockerPass" | docker login --username "$DockerUserName" --password-stdin
            docker push topiaas/portal:$TAG
            docker push topiaas/portalworker:$TAG
            
          fi
          
  build-engine:
    docker:
      - image: circleci/golang:1.15
      
    steps:
      - checkout
      
      - setup_remote_docker:
          version: 19.03.13
          
      - run: |
          if [ -z $(git diff --name-only HEAD HEAD~1 | grep engine | head -n 1 ) ]; then 
          
            circleci-agent step halt
            
          else
          
            if [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]]; then
                TAG="latest"
            else
                TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
            fi
            
            docker build -t topiaas/engine:$TAG -f ./engine/orangeml/Dockerfile.orange ./engine/orangeml
            echo "$DockerPass" | docker login --username "$DockerUserName" --password-stdin
            docker push topiaas/engine:$TAG
            
          fi
         

workflows:
  default:
    jobs:
      - build-portal:
          context: DockerPass
      - build-engine:
          context: DockerPass
