---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topiaas-deployment
  labels:
    app: topiaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: topiaas
  template:
    metadata:
      labels:
        app: topiaas
    spec:
      serviceAccountName: app-manager-service-account
      containers:
        - name: topiaas
          image: topiaas/portal:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              value: Topiaas
            - name: FLASK_CONFIG
              value: production
            - name: REDISTOGO_URL
              value: "http://redis-cluster-master:6379"
            - name: DATABASE_USER
              value: devel
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_SERVICE_NAME
              value: postgres-postgresql-ha-pgpool
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql-ha-postgresql
                  key: postgresql-password
            - name: SECRET_KEY
              value: sercet_key #TODO: change
